name: Unit and Integration Tests x
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUNNER_TEMP: ${{ startsWith(matrix.os, 'windows') && 'D:\\workspace\\runner_temp' || '' }}
      GOTMPDIR: ${{ startsWith(matrix.os, 'windows') && 'D:\\workspace\\go_tmp' || '' }}

    steps:
      - name: Set working directory to D drive if Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          mkdir D:\workspace
          xcopy /E /H /C /I . D:\workspace
          cd D:\workspace
          mkdir D:\workspace\runner_temp
          mkdir D:\workspace\go_tmp

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Print RUNNER_TEMP environment variable
        run: echo "RUNNER_TEMP is $RUNNER_TEMP"

      - name: Download dependencies
        run: go mod download

      - name: Run unit and integration tests
        run: go test -race -tags=integration ./...

      - name: Build
        run: go build -v ./cmd/gh

  integration-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false
          

      - name: Build executable
        run: make

      - name: Run attestation command set integration tests
        shell: bash
        run: |
          ./test/integration/attestation-cmd/run-all-tests.sh "${{ matrix.os }}"
